### ISSUE TITLE
feat(norm): add `foreign` property to the receiver's declaration

### ISSUE THREAD

**Issue by temich** [toa-io/toa#232]
# Change Requests

- [x] feat: add `foreign` property with default `false` value to the [schema](https://github.com/toa-io/toa/blob/main/runtime/norm/src/.component/schema.yaml)
- [x] feat: add `foreign` property default `true` value to [normalization](https://github.com/toa-io/toa/tree/main/runtime/norm/src/.component/.normalize) (if `binding` is defined)

**Comment by burlakilia** [comment]
PR https://github.com/toa-io/toa/pull/233/files
