### ISSUE TITLE
Support standard $ref across whole manifest

### ISSUE THREAD

**Issue by tinovyatkin** [toa-io/toa#666]
We currently relying on concise features `&` / `*` to be able to link shape of an entity / input to some output field. If we want to deprecate non-standard concise syntax we have to implement support for standard `$ref` / $def` that would work across whole initial manifest rather than individual subschemas.

References:
1. https://json-schema.org/understanding-json-schema/structuring
2. https://github.com/APIDevTools/json-schema-ref-parser

**Comment by temich** [comment]
[Know your enemy](https://yaml.org/spec/1.2.2/#692-node-anchors).
